#! /bin/sh

# Hotkey listener
sxhkd &

# Boot polybar
killall -q polybar
~/scripts/polybar_launch.sh

# Reset any previously registered external monitors
# bspc monitor DP-2 -r
# bspc monitor HDMI-1 -r
# bspc monitor HDMI-2 -r

# Single screen
# bspc monitor eDP-1 -d 1 2 3 4 5

# Left side USB-C display (laptop is main)
# bspc monitor DP-2 -d 1 2
# bspc monitor eDP-1 -d 3 4 5

# Left side HDMI display (HDMI is main)
# bspc monitor HDMI-1 -d 1 2 3 4
# bspc monitor eDP-1 -d 5

# Borders
bspc config border_width         3
bspc config focused_border_color "#98C379"
bspc config window_gap           2

# Misc
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config top_padding 0

bspc rule -a Emacs state=tiled
