#! /bin/sh

sxhkd &

bspc monitor eDP-1 -d 1 2 3 4
bspc monitor HDMI-1 -d 5 6

bspc config border_width         3
bspc config focused_border_color "#98C379"
bspc config window_gap           2

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config -m eDP-1 top_padding 0
bspc config -m eDP-1 bottom_padding 42

