#! /bin/sh

# Hotkey listener
killall -q sxhkd &
sxhkd &

# Boot polybar
killall -q polybar
~/scripts/polybar_launch.sh &

# Config desktops
~/scripts/bspwm_auto_config.sh

# Borders
bspc config border_width         3
bspc config focused_border_color "#98C379"
bspc config window_gap           2

# Misc
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config top_padding 0

bspc rule -a Emacs state=tiled
